### ISSUE TITLE
跑不通，报了一个错误

### ISSUE THREAD

**Issue by pc10201** [x-spiders/aiss-spider#1]
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    download_info()
  File "/data/wwwroot/default/aiss-spider/download_info.py", line 11, in download_info
    if not page_json['data']['list']:
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by yijingping** [comment]
```
curl -H 'Host: api.pmkoo.cn' -H 'Accept: */*' -H 'Accept-Language: zh-Haq=1, en-CN;q=0.9' -H 'User-Agent: aiss/1.0 (iPhone; iOS 10.2; Scale/2.00)' --data "page=1&userId=153044" --compressed 'http://api.pmkoo.cn/aiss/suite/suiteList.do'
```
你命令行执行一下这个看有返回吗？ 可能你那次请求没返回东西？多试几次

**Comment by yijingping** [comment]
如果还有问题，请把下面这个文件放到 `data/` 目录下,然后执行 `python download_pictures.py`

[info.txt](https://github.com/x-spiders/aiss-spider/files/721856/info.txt)
